name: Update Action

on: ['push', 'pull_request']

permissions:
  packages: read
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-action:
    runs-on: ubuntu-latest
    steps:
      - name: Update action.yml
        uses: alvelive/update-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
          sha: ${{ github.sha }}

  test:
    name: Test Custom Docker Build and Push
    runs-on: ubuntu-latest
    needs: update-action
    env:
      branch: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test Custom Docker Build and Push
        uses: alvelive/build@v1
        with:
          repo: ${{ github.event.repository.name }}
          # branch: ${{ env.branch }}
          # Empty commit hash will evaluate to "latest"
          # commit-hash: latest
          docker-password: ${{ secrets.ALVE_ORG_DOCKER_PASSWORD }}
          docker-username: ${{ secrets.ALVE_ORG_DOCKER_USERNAME }}
          env-file: ${{ secrets.DEV_ENV_FILE }}
          npmrc: ${{ format(secrets.ALVE_ORG_NPMRC_TEMPLATE, secrets.GITHUB_TOKEN) }}
          push: true
