name: Update Action

on: ['push', 'pull_request']

permissions:
  packages: read
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-action:
    name: Update Action file with new script url
    runs-on: ubuntu-latest
    env:
      SCRIPT_FILE: 'parse_image_name.sh'
      INPUT_FILE: 'action-template.yml'
      OUTPUT_FILE: 'action.yml'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare README.md
        run: |
          INSTALL_URL="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/${{ env.SCRIPT_FILE }}"
          sed "s|{{parse_image_name}}|$INSTALL_URL|g" ${{ env.INPUT_FILE }} > ${{ env.OUTPUT_FILE }}

      - name: Commit and push README.md
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add ${{ env.OUTPUT_FILE }}
          git commit -m "Update ${{ env.OUTPUT_FILE }} to reflect new release"
          git push

  test:
    name: Test Custom Docker Build and Push
    runs-on: ubuntu-latest
    needs: update-action
    env:
      branch: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test Custom Docker Build and Push
        uses: alvelive/build@v1
        with:
          repo: ${{ github.event.repository.name }}
          # branch: ${{ env.branch }}
          # Empty commit hash will evaluate to "latest"
          # commit-hash: latest
          docker-password: ${{ secrets.ALVE_ORG_DOCKER_PASSWORD }}
          docker-username: ${{ secrets.ALVE_ORG_DOCKER_USERNAME }}
          env-file: ${{ secrets.DEV_ENV_FILE }}
          npmrc: ${{ format(secrets.ALVE_ORG_NPMRC_TEMPLATE, secrets.GITHUB_TOKEN) }}
          push: true
